name: Update publication list

on:
  push:
    paths:
    - 'scripts/bibgen.py'
    - 'scripts/pubstats.py'
    - '_data/custom_bib.yml'
    - '.github/workflows/update_publications.yml'
  schedule:
    - cron: '0 4 * * *'

jobs:
  update-publication-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Update publication list
      id: main
      run: |
        export ADS_API_KEY=${{ secrets.ADS_API_KEY }}
        python scripts/bibgen.py
    - name: Update from Google Scholar
      id: scholarly
      run: python scripts/pubstats.py
      continue-on-error: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        token: ${{ secrets.PAT }}
        commit-message: update publication list
        delete-branch: true
        title: "[bot] publication list update"
        body: |
           This is an auto-generated PR to update the publication list.
        branch: actions/update-publication-list
        labels: 'auto-update-pubs'

